### ISSUE TITLE
Error in update-vm.sh

### ISSUE THREAD

**Issue by damphyr** [Zuehlke/linux-developer-vm#9]
I switched the Vagrantfile to use Ubuntu Server 14.04 LTS ("ubuntu/trusty64") and stumbled on an error in line 68.
That eval() call fails consistently. Did a bit of digging and I don't really think you need to eval there at all since there is no shell substitution going on in the command line that you might want to defer.

`chef shell-init bash` should do it.

**Comment by damphyr** [comment]
I'm moving things around and putting together something close to windev-example using the same script structure so that we can call `chef.sh config.json` in the VM and have the same workflow. 
<rant mode on>
I do so much love bash - there's actually no need for all those stupid batch files and I get proper error handling.
😝 
<rant mode off>

**Comment by tknerr** [comment]
Sweet, will this be lin-dev cookbook then? :-)
Am 25.05.2016 1:03 nachm. schrieb "Vassilis Rizopoulos" <
notifications@github.com>:

**Comment by tknerr** [comment]
As far as the README says "chef shell-init" only emits the commands to set
up yout shell with chefdk as the primary ruby environment, which you have
to eval then:
https://github.com/chef/chef-dk/blob/master/README.md#using-chefdk-as-your-primary-development-environment

Seems weird, why shouldn't it work with Ubuntu trusty server then?

Btw: just curious, why do you want to use Ubuntu server instead of desktop
for a developer VM?
Am 26.05.2016 2:03 vorm. schrieb "Torben Knerr" mail@tknerr.de:

**Comment by tknerr** [comment]
As far as the README says "chef shell-init" only emits the commands to set
up yout shell with chefdk as the primary ruby environment, which you have
to eval then:
https://github.com/chef/chef-dk/blob/master/README.md#using-chefdk-as-your-primary-development-environment

Seems weird, why shouldn't it work with Ubuntu trusty server then?

Btw: just curious, why do you want to use Ubuntu server instead of desktop
for a developer VM?
Am 25.05.2016 1:31 nachm. schrieb "Vassilis Rizopoulos" <
notifications@github.com>:

**Comment by tknerr** [comment]
fixed via 46d294f645eca8e5b7df2d677c81a64e3b2df2eb
